name: api
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.8.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py312h66e93f0_5
  - bcrypt=4.3.0=py312h868fb18_2
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.1.31=hbd8a1cb_1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py312h35888ee_1
  - click=8.1.8=pyh707e725_0
  - cryptography=44.0.2=py312hda17c39_0
  - dnspython=2.7.0=pyhff2d567_1
  - email-validator=2.2.0=pyhd8ed1ab_1
  - email_validator=2.2.0=hd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - fastapi=0.115.11=pyh29332c3_0
  - fastapi-cli=0.0.7=pyhd8ed1ab_0
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.7=pyh29332c3_1
  - httptools=0.6.4=py312h4c3975b_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - ld_impl_linux-64=2.43=h1423503_5
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libsqlite=3.49.1=hee588c1_2
  - libstdcxx=14.2.0=h8f9b012_2
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py312h178313f_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.2.3=py312h72c5963_0
  - openssl=3.4.1=h7b32b05_0
  - pandas=2.2.3=py312hf9745cd_3
  - passlib=1.7.4=pyhd8ed1ab_2
  - pip=25.0.1=pyh8b19718_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.10.6=pyh3cfb1c2_0
  - pydantic-core=2.27.2=py312h12e396e_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - python=3.12.9=h9e4cc4f_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.0.1=pyhd8ed1ab_1
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h178313f_2
  - readline=8.2=h8c095d6_2
  - rich=13.9.4=pyhd8ed1ab_1
  - rich-toolkit=0.11.3=pyh29332c3_0
  - setuptools=75.8.2=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - starlette=0.46.1=pyha770c72_0
  - termcolor=2.5.0=pyhd8ed1ab_1
  - tk=8.6.13=noxft_hd72426e_102
  - typer=0.15.2=pyhff008b6_0
  - typer-slim=0.15.2=pyh29332c3_0
  - typer-slim-standard=0.15.2=h801b22e_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2025a=h78e105d_0
  - uvicorn=0.34.0=pyh31011fe_0
  - uvicorn-standard=0.34.0=h31011fe_0
  - uvloop=0.21.0=py312h66e93f0_1
  - watchfiles=1.0.4=py312h12e396e_0
  - websockets=15.0.1=py312h5253ce2_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.2.5=h280c20c_3
  - pip:
      - charset-normalizer==3.4.1
      - jq==1.8.0
      - nuitka==2.7.4
      - ordered-set==4.1.0
      - requests==2.32.3
      - urllib3==2.4.0
      - zstandard==0.23.0
prefix: /root/miniconda3/envs/api
